#include <iostream>
#include <cctype>
#include <windows.h>
using namespace std;
 void gamemenu();
 void gotoxy(int x,int y);
HANDLE h = GetStdHandle(STD_OUTPUT_HANDLE);
main()
{
    gamemenu();
}
 void gamemenu()
{
    int x=1, y=2;
    gotoxy(x, y);                         
    cout<<"                                                                                          ";
    SetConsoleTextAttribute(h, 6);
    cout << "============================================";
    SetConsoleTextAttribute(h, 15);
    cout << "           "<<endl;
Sleep(30);

    gotoxy(x, y+1);                         
    cout<<"                                                                                             +";
    SetConsoleTextAttribute(h, 15);
    cout << "+";
    SetConsoleTextAttribute(h, 6);
    cout << "+";
    SetConsoleTextAttribute(h, 15);
    cout << "+";
    SetConsoleTextAttribute(h, 6);
    cout << "+";
    SetConsoleTextAttribute(h, 15);
    cout << "+";
    SetConsoleTextAttribute(h, 6);
    cout << "+";
    SetConsoleTextAttribute(h, 15);
    cout << "+";
    SetConsoleTextAttribute(h, 6);
    cout << "+";
    SetConsoleTextAttribute(h, 15);
    cout << "+";
    SetConsoleTextAttribute(h, 6);
    cout << "+";
    SetConsoleTextAttribute(h, 15);
    cout << "+";
    SetConsoleTextAttribute(h, 6);
    cout << "+";
    SetConsoleTextAttribute(h, 15);
    cout << "+";
    SetConsoleTextAttribute(h, 6);
    cout << "+";
    SetConsoleTextAttribute(h, 15);
    cout << "+";
    SetConsoleTextAttribute(h, 6);
    cout << "+";
    SetConsoleTextAttribute(h, 15);
    cout << "+";
    SetConsoleTextAttribute(h, 6);
    cout << "+";
    SetConsoleTextAttribute(h, 15);
    cout << "+";
    SetConsoleTextAttribute(h, 6);
    cout << "+";
    SetConsoleTextAttribute(h, 15);
    cout << "+";
    SetConsoleTextAttribute(h, 6);
    cout << "+";
    SetConsoleTextAttribute(h, 15);
    cout << "+";
    SetConsoleTextAttribute(h, 6);
    cout << "+";
    SetConsoleTextAttribute(h, 15);
    cout << "+";
    SetConsoleTextAttribute(h, 6);
    cout << "+";
    SetConsoleTextAttribute(h, 15);
    cout << "+";
    SetConsoleTextAttribute(h, 6);
    cout << "+";
    SetConsoleTextAttribute(h, 15);
    cout << "+";
    SetConsoleTextAttribute(h, 6);
    cout << "+";
    SetConsoleTextAttribute(h, 15);
    cout << "+";
    SetConsoleTextAttribute(h, 6);
    cout << "+";
    SetConsoleTextAttribute(h, 15);
    cout << "+";
    SetConsoleTextAttribute(h, 6);
    cout << "+";
    SetConsoleTextAttribute(h, 15);
    cout << "+";
    SetConsoleTextAttribute(h, 6);
    cout << "+";
    SetConsoleTextAttribute(h, 15);
    cout << "+              "<<endl;
Sleep(30);

    gotoxy(x, y+2);                         
    SetConsoleTextAttribute(h, 4);
    cout<<"    _.__.";
    SetConsoleTextAttribute(h, 1);
    cout << "        ";
    SetConsoleTextAttribute(h, 4);
    cout << "        ";
    SetConsoleTextAttribute(h, 1);
    cout << "    _      _  ";
    SetConsoleTextAttribute(h, 4);
    cout << "__    ";
    SetConsoleTextAttribute(h, 1);
    cout << "         ";
    SetConsoleTextAttribute(h, 4);
    cout << "                           ";
    SetConsoleTextAttribute(h, 6);
    cout << "--------------------------------------------------        "<<endl;
Sleep(30);

    gotoxy(x, y+3);                         
    SetConsoleTextAttribute(h, 4);
    cout<<"     \\__  |   |";
    SetConsoleTextAttribute(h, 1);
    cout << "  __  ";
    SetConsoleTextAttribute(h, 4);
    cout << " _ _  ";
    SetConsoleTextAttribute(h, 1);
    cout << "  /    \\    /  \\";
    SetConsoleTextAttribute(h, 4);
    cout << "|__| ";
    SetConsoleTextAttribute(h, 1);
    cout << "___   ";
    SetConsoleTextAttribute(h, 4);
    cout << "                             ";
    SetConsoleTextAttribute(h, 6);
    cout << "    --------------------------------------------------     "<<endl;
Sleep(30);

    gotoxy(x, y+4);                         
    SetConsoleTextAttribute(h, 4);
    cout<<"     /   |   |";
    SetConsoleTextAttribute(h, 1);
    cout << " /  _ \\";
    SetConsoleTextAttribute(h, 4);
    cout << " |  |  \\";
    SetConsoleTextAttribute(h, 1);
    cout << "   \\   \\/\\/   /";
    SetConsoleTextAttribute(h, 4);
    cout << "|  |";
    SetConsoleTextAttribute(h, 1);
    cout << "/     \\";
    SetConsoleTextAttribute(h, 4);
    cout << "                               ";
    SetConsoleTextAttribute(h, 6);
    cout << " --------------------------------------------------  "<<endl;
Sleep(30);

    gotoxy(x, y+5);                         
    SetConsoleTextAttribute(h, 4);
    cout<<"     \\__   |";
    SetConsoleTextAttribute(h, 1);
    cout << "(  <_> )";
    SetConsoleTextAttribute(h, 4);
    cout << "|  |  / ";
    SetConsoleTextAttribute(h, 1);
    cout << "   \\        / ";
    SetConsoleTextAttribute(h, 4);
    cout << "|  |";
    SetConsoleTextAttribute(h, 1);
    cout << "|   |  \\  ";
    SetConsoleTextAttribute(h, 4);
    cout << "                            ";
    SetConsoleTextAttribute(h, 6);
    cout << "   --------------------------------------------------     "<<endl;
Sleep(30);

    gotoxy(x, y+6);                         
    SetConsoleTextAttribute(h, 4);
    cout<<"     / __|";
    SetConsoleTextAttribute(h, 1);
    cout << "  \\__/";
    SetConsoleTextAttribute(h, 4);
    cout << " |__/ ";
    SetConsoleTextAttribute(h, 1);
    cout << "       \\__/\\  /";
    SetConsoleTextAttribute(h, 4);
    cout << "  |__|";
    SetConsoleTextAttribute(h, 1);
    cout << "|_|  / ";
    SetConsoleTextAttribute(h, 4);
    cout << "                             ";
    SetConsoleTextAttribute(h, 6);
    cout << "        -----  ------------------------------------  -----     "<<endl;
Sleep(30);

    gotoxy(x, y+7);                         
    cout<<"     \\/                                \\/            \\/                                 ----   ----------------------------------   ----      "<<endl;
Sleep(30);

    gotoxy(x, y+8);                         
    cout<<"                                                                                        ----   ----------------------------------   ----         "<<endl;
Sleep(30);

    gotoxy(x, y+9);                         
    cout<<"                                                                                         ----   --------------------------------   ----          "<<endl;
Sleep(30);

    gotoxy(x, y+10);                         
    cout<<"                                                                                          ----  --------------------------------  ----           "<<endl;
Sleep(30);

    gotoxy(x, y+11);                         
    cout<<"                                                                                           ----  ------------------------------  ----            "<<endl;
Sleep(30);

    gotoxy(x, y+12);                         
    cout<<"                                                                                            ----- ---------------------------- -----             "<<endl;
Sleep(30);

    gotoxy(x, y+13);                         
    cout<<"                                                                                              -------------------------------------              "<<endl;
Sleep(30);

    gotoxy(x, y+14);                         
    cout<<"                                                                                               ----------------------------------                "<<endl;
Sleep(30);

    gotoxy(x, y+15);                         
    cout<<"                                                                                                 ------------------------------                  "<<endl;
Sleep(30);

    gotoxy(x, y+16);                         
    cout<<"                                                                                                   --------------------------                    "<<endl;
Sleep(30);

    gotoxy(x, y+17);                         
    cout<<"                                                                                                      --------------------                       "<<endl;
Sleep(30);

    gotoxy(x, y+18);                         
    cout<<"                                                                                                         --------------                          "<<endl;
Sleep(30);

    gotoxy(x, y+19);                         
    cout<<"                                                                                                           ----------                            "<<endl;
Sleep(30);

    gotoxy(x, y+20);                         
    cout<<"                                                                                                           ";
    SetConsoleTextAttribute(h, 15);
    cout << "==========";
    SetConsoleTextAttribute(h, 6);
    cout << "                            "<<endl;
Sleep(30);

    gotoxy(x, y+21);                         
    cout<<"                                                                                                           ";
    SetConsoleTextAttribute(h, 15);
    cout << " ======== ";
    SetConsoleTextAttribute(h, 6);
    cout << "                            "<<endl;
Sleep(30);

    gotoxy(x, y+22);                         
    cout<<"                                                                                                           ";
    SetConsoleTextAttribute(h, 15);
    cout << "  -====-  ";
    SetConsoleTextAttribute(h, 6);
    cout << "                            "<<endl;
Sleep(30);

    gotoxy(x, y+23);                         
    cout<<"                                                                                                            --------                             "<<endl;
Sleep(30);

    gotoxy(x, y+24);                         
    cout<<"                                                                                                           ----------                            "<<endl;
Sleep(30);

    gotoxy(x, y+25);                         
    cout<<"                                                                                                          ------------                           "<<endl;
Sleep(30);

    gotoxy(x, y+26);                         
    cout<<"                                                                                                        ----------------                         "<<endl;
Sleep(30);

    gotoxy(x, y+27);                         
    cout<<"                                                                                                      --------------------                       "<<endl;
Sleep(30);

    gotoxy(x, y+28);                         
    cout<<"                                                                                                 ";
    SetConsoleTextAttribute(h, 15);
    cout << "+";
    SetConsoleTextAttribute(h, 6);
    cout << "+";
    SetConsoleTextAttribute(h, 15);
    cout << "+";
    SetConsoleTextAttribute(h, 6);
    cout << "+";
    SetConsoleTextAttribute(h, 15);
    cout << "+";
    SetConsoleTextAttribute(h, 6);
    cout << "+";
    SetConsoleTextAttribute(h, 15);
    cout << "+";
    SetConsoleTextAttribute(h, 6);
    cout << "+";
    SetConsoleTextAttribute(h, 15);
    cout << "+";
    SetConsoleTextAttribute(h, 6);
    cout << "+";
    SetConsoleTextAttribute(h, 15);
    cout << "+";
    SetConsoleTextAttribute(h, 6);
    cout << "+";
    SetConsoleTextAttribute(h, 15);
    cout << "+";
    SetConsoleTextAttribute(h, 6);
    cout << "+";
    SetConsoleTextAttribute(h, 15);
    cout << "+";
    SetConsoleTextAttribute(h, 6);
    cout << "+";
    SetConsoleTextAttribute(h, 15);
    cout << "+";
    SetConsoleTextAttribute(h, 6);
    cout << "+";
    SetConsoleTextAttribute(h, 15);
    cout << "+";
    SetConsoleTextAttribute(h, 6);
    cout << "+";
    SetConsoleTextAttribute(h, 15);
    cout << "+";
    SetConsoleTextAttribute(h, 6);
    cout << "+";
    SetConsoleTextAttribute(h, 15);
    cout << "+";
    SetConsoleTextAttribute(h, 6);
    cout << "+";
    SetConsoleTextAttribute(h, 15);
    cout << "+";
    SetConsoleTextAttribute(h, 6);
    cout << "+";
    SetConsoleTextAttribute(h, 15);
    cout << "+";
    SetConsoleTextAttribute(h, 6);
    cout << "+";
    SetConsoleTextAttribute(h, 15);
    cout << "+";
    SetConsoleTextAttribute(h, 6);
    cout << "+";
    SetConsoleTextAttribute(h, 15);
    cout << "+";
    cout << "                  "<<endl;
Sleep(30);

    gotoxy(x, y+29);                         
    cout<<"                                                                                                  ";
    SetConsoleTextAttribute(h, 15);
    cout << "+";
    SetConsoleTextAttribute(h, 6);
    cout << "+";
    SetConsoleTextAttribute(h, 15);
    cout << "+";
    SetConsoleTextAttribute(h, 6);
    cout << "+";
    SetConsoleTextAttribute(h, 15);
    cout << "+";
    SetConsoleTextAttribute(h, 6);
    cout << "+";
    SetConsoleTextAttribute(h, 15);
    cout << "+";
    SetConsoleTextAttribute(h, 6);
    cout << "+";
    SetConsoleTextAttribute(h, 15);
    cout << "+";
    SetConsoleTextAttribute(h, 6);
    cout << "+";
    SetConsoleTextAttribute(h, 15);
    cout << "+";
    SetConsoleTextAttribute(h, 6);
    cout << "+";
    SetConsoleTextAttribute(h, 15);
    cout << "+";
    SetConsoleTextAttribute(h, 6);
    cout << "+";
    SetConsoleTextAttribute(h, 15);
    cout << "+";
    SetConsoleTextAttribute(h, 6);
    cout << "+";
    SetConsoleTextAttribute(h, 15);
    cout << "+";
    SetConsoleTextAttribute(h, 6);
    cout << "+";
    SetConsoleTextAttribute(h, 15);
    cout << "+";
    SetConsoleTextAttribute(h, 6);
    cout << "+";
    SetConsoleTextAttribute(h, 15);
    cout << "+";
    SetConsoleTextAttribute(h, 6);
    cout << "+";
    SetConsoleTextAttribute(h, 15);
    cout << "+";
    SetConsoleTextAttribute(h, 6);
    cout << "+";
    SetConsoleTextAttribute(h, 15);
    cout << "+";
    SetConsoleTextAttribute(h, 6);
    cout << "+";
    SetConsoleTextAttribute(h, 15);
    cout << "+";
    SetConsoleTextAttribute(h, 6);
    cout << "+";
    SetConsoleTextAttribute(h, 15);
    cout << "+";
    cout << "                   "<<endl;
Sleep(30);

    gotoxy(x, y+30);                         
    cout<<"                                                                                                   ";
    SetConsoleTextAttribute(h, 6);
    cout << "==";
    SetConsoleTextAttribute(h, 15);
    cout << "==";
    SetConsoleTextAttribute(h, 6);
    cout << "=====";
    SetConsoleTextAttribute(h, 15);
    cout << "==";
    SetConsoleTextAttribute(h, 6);
    cout << "==";
    SetConsoleTextAttribute(h, 15);
    cout << "==";
    SetConsoleTextAttribute(h, 6);
    cout << "==";
    SetConsoleTextAttribute(h, 15);
    cout << "===";
    SetConsoleTextAttribute(h, 6);
    cout << "===";
    SetConsoleTextAttribute(h, 15);
    cout << "==";
    SetConsoleTextAttribute(h, 6);
    cout << "==                    "<<endl;
Sleep(30);

    gotoxy(x, y+31);                         
    cout<<"                                                                                                   ";
    SetConsoleTextAttribute(h, 6);
    cout << "==";
    SetConsoleTextAttribute(h, 15);
    cout << "==";
    SetConsoleTextAttribute(h, 6);
    cout << "=====";
    SetConsoleTextAttribute(h, 15);
    cout << "==";
    SetConsoleTextAttribute(h, 6);
    cout << "==";
    SetConsoleTextAttribute(h, 15);
    cout << "==";
    SetConsoleTextAttribute(h, 6);
    cout << "==";
    SetConsoleTextAttribute(h, 15);
    cout << "==";
    SetConsoleTextAttribute(h, 6);
    cout << "=";
    SetConsoleTextAttribute(h, 15);
    cout << "=";
    SetConsoleTextAttribute(h, 6);
    cout << "==";
    SetConsoleTextAttribute(h, 15);
    cout << "==";
    SetConsoleTextAttribute(h, 6);
    cout << "==                    "<<endl;
Sleep(30);

    gotoxy(x, y+32);                         
    cout<<"                                                                                                   ";
    SetConsoleTextAttribute(h, 6);
    cout << "==";
    SetConsoleTextAttribute(h, 15);
    cout << "==";
    SetConsoleTextAttribute(h, 6);
    cout << "==";
    SetConsoleTextAttribute(h, 15);
    cout << "=";
    SetConsoleTextAttribute(h, 6);
    cout << "==";
    SetConsoleTextAttribute(h, 15);
    cout << "==";
    SetConsoleTextAttribute(h, 6);
    cout << "==";
    SetConsoleTextAttribute(h, 15);
    cout << "==";
    SetConsoleTextAttribute(h, 6);
    cout << "==";
    SetConsoleTextAttribute(h, 15);
    cout << "==";
    SetConsoleTextAttribute(h, 6);
    cout << "==";
    SetConsoleTextAttribute(h, 15);
    cout << "=";
    SetConsoleTextAttribute(h, 6);
    cout << "=";
    SetConsoleTextAttribute(h, 15);
    cout << "==";
    SetConsoleTextAttribute(h, 6);
    cout << "==                    "<<endl;
Sleep(30);

    gotoxy(x, y+33);                         
    cout<<"                                                                                                   ";
    SetConsoleTextAttribute(h, 6);
    cout << "==";
    SetConsoleTextAttribute(h, 15);
    cout << "==";
    SetConsoleTextAttribute(h, 6);
    cout << "==";
    SetConsoleTextAttribute(h, 15);
    cout << "=";
    SetConsoleTextAttribute(h, 6);
    cout << "==";
    SetConsoleTextAttribute(h, 15);
    cout << "==";
    SetConsoleTextAttribute(h, 6);
    cout << "==";
    SetConsoleTextAttribute(h, 15);
    cout << "==";
    SetConsoleTextAttribute(h, 6);
    cout << "==";
    SetConsoleTextAttribute(h, 15);
    cout << "==";
    SetConsoleTextAttribute(h, 6);
    cout << "===";
    SetConsoleTextAttribute(h, 15);
    cout << "===";
    SetConsoleTextAttribute(h, 6);
    cout << "==                    "<<endl;
Sleep(30);

    gotoxy(x, y+34);                         
    cout<<"                                                                                                   ";
    SetConsoleTextAttribute(h, 6);
    cout << "==";
    SetConsoleTextAttribute(h, 15);
    cout << "==";
    SetConsoleTextAttribute(h, 15);
    cout << "=====";
    SetConsoleTextAttribute(h, 15);
    cout << "==";
    SetConsoleTextAttribute(h, 6);
    cout << "==";
    SetConsoleTextAttribute(h, 15);
    cout << "==";
    SetConsoleTextAttribute(h, 6);
    cout << "==";
    SetConsoleTextAttribute(h, 15);
    cout << "==";
    SetConsoleTextAttribute(h, 6);
    cout << "====";
    SetConsoleTextAttribute(h, 15);
    cout << "==";
    SetConsoleTextAttribute(h, 6);
    cout << "==                    "<<endl;
Sleep(30);

    gotoxy(x, y+35);                         
    cout<<"                                                                                                 *******************************"<<endl;
Sleep(30);

    gotoxy(x, y+36);  

}
void gotoxy(int x,int y)
{
    COORD coordinates;     // coordinates is declared as COORD
    coordinates.X = x;     // defining x-axis
    coordinates.Y = y;     //defining  y-axis
    SetConsoleCursorPosition(GetStdHandle(STD_OUTPUT_HANDLE),coordinates);   
}